variables:
- name: BuildParameters.ArtifactName
  value: drop
trigger:
  branches:
    include:
    - main
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_2
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
    displayName: 'Run Azure Cosmos DB Emulator'
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    env:
      CosmosDbUri: $(CosmosDbEmulator.Endpoint)
    inputs:
      command: test
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      projects: '**/*.sln'
      arguments: -o $(build.artifactstagingdirectory) -c Release
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: $(BuildParameters.ArtifactName)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
